version: '3'

services:
  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - "8081:80"
    volumes:
      - "./www:/var/www"
      - "./nginx/sites:/etc/nginx/conf.d"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./log/nginx:/var/log/nginx"
    depends_on:
      - php

  php:
    image: php:7.1-fpm
    restart: always
    volumes:
      - "./www:/var/www"
