version: '3'

services:
  nginx:
    image: nginx:1.13
    restart: always
    ports:
      - "8081:80"
    volumes:
      - "./www:/var/www"
      - "./nginx/sites:/etc/nginx/conf.d"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./log/nginx:/var/log/nginx"
    depends_on:
      - php

  php:
    build: 
      context: "./"
      dockerfile: "Dockerfile-php"
    image: phpcustom
    restart: always
    volumes:
      - "./www:/var/www"
    depends_on:
      - mariadb
    links:
      - "mariadb:mysql"

  mariadb:
    image: mariadb:10.3
    restart: always
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=dev"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    ports:
      - "8083:80"
    environment:
      - "PMA_HOST=mysql"
      - "MYSQL_ROOT_PASSWORD=dev"
    depends_on:
      - php
    links:
      - "mariadb:mysql"
